// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATrfj4Shh6jun8aIU5hZ2PNA3UVasXj2o',
    appId: '1:855797727266:web:6212a8cac6c33e38788a7b',
    messagingSenderId: '855797727266',
    projectId: 'ecommerce-d7627',
    authDomain: 'ecommerce-d7627.firebaseapp.com',
    storageBucket: 'ecommerce-d7627.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYIlMzd0bA0p53EIvVRSbPatgCQZxIVII',
    appId: '1:855797727266:android:115735cd68e5b102788a7b',
    messagingSenderId: '855797727266',
    projectId: 'ecommerce-d7627',
    storageBucket: 'ecommerce-d7627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeQqBBuBUtjimNHD_PasAPvhrGaoXM9aQ',
    appId: '1:855797727266:ios:255becebde9c7bb2788a7b',
    messagingSenderId: '855797727266',
    projectId: 'ecommerce-d7627',
    storageBucket: 'ecommerce-d7627.appspot.com',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeQqBBuBUtjimNHD_PasAPvhrGaoXM9aQ',
    appId: '1:855797727266:ios:fadc31f9b41da95b788a7b',
    messagingSenderId: '855797727266',
    projectId: 'ecommerce-d7627',
    storageBucket: 'ecommerce-d7627.appspot.com',
    iosBundleId: 'com.example.course.RunnerTests',
  );
}
